#测试用基础表USERT
DROP TABLE "USERT";

CREATE TABLE "USERT" (
  "ID" VARCHAR(32) NOT NULL,
  "NAME" VARCHAR(20) DEFAULT NULL,
  "PASSWORD" VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

#测试用自增表IDTY
DROP TABLE "IDTY";

CREATE TABLE "IDTY" (
  "ID" INTEGER IDENTITY(1,1) NOT NULL,
  "NAME" VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY ("ID")
);